const BLE_SERVICE = "6e400001-b5a3-f393-e0a9-e50e24dcca9e";
const BLE_RX = "6e400002-b5a3-f393-e0a9-e50e24dcca9e";
const BLE_TX = "6e400003-b5a3-f393-e0a9-e50e24dcca9e";
const SAVED_KEY = "meshcore-repeater-status-list-v2";
const CMD = { APP_START: 1, GET_CONTACTS: 4, SET_DEVICE_TIME: 6, DEVICE_QUERY: 22, SEND_LOGIN: 26, SEND_STATUS_REQ: 27 };
const RESP = { ERROR: 1, CONTACTS_END: 4, CONTACT: 3, DEVICE_INFO: 13, SELF_INFO: 5, LOGIN_SUCCESS: 133, LOGIN_FAIL: 134, STATUS: 135 };
const TYPE_REPEATER = 2;
const state = { device: null, rx: null, tx: null, waiters: [], contacts: [], saved: loadSaved(), connected: false, intentionalDisconnect: false, reconnecting: false, search: "" };
const el = { version: document.querySelector("#version"), connection: document.querySelector("#connectionState"), connect: document.querySelector("#connect"), disconnect: document.querySelector("#disconnect"), repeaterSearch: document.querySelector("#repeaterSearch"), repeater: document.querySelector("#repeater"), password: document.querySelector("#password"), syncTime: document.querySelector("#syncTime"), status: document.querySelector("#statusButton"), save: document.querySelector("#saveRepeater"), remove: document.querySelector("#removeRepeater"), export: document.querySelector("#exportRepeaters"), import: document.querySelector("#importRepeaters"), importFile: document.querySelector("#importFile"), result: document.querySelector("#result"), title: document.querySelector("#resultTitle"), text: document.querySelector("#resultText"), stats: document.querySelector("#stats"), notice: document.querySelector("#notice"), noticeTitle: document.querySelector("#noticeTitle"), noticeText: document.querySelector("#noticeText"), log: document.querySelector("#log"), support: document.querySelector("#support") };
function loadSaved(){try{const value=JSON.parse(localStorage.getItem(SAVED_KEY)||"[]");return Array.isArray(value)?value.filter(validRepeater):[]}catch{return[]}}
function validRepeater(value){return value&&/^[0-9a-f]{64}$/i.test(value.key)&&typeof value.name==="string"}
function persistSaved(){localStorage.setItem(SAVED_KEY,JSON.stringify(state.saved))}
function u32(data,offset){return(data[offset]|data[offset+1]<<8|data[offset+2]<<16|data[offset+3]<<24)>>>0}
function s16(data,offset){const value=data[offset]|data[offset+1]<<8;return value>32767?value-65536:value}
function u16(data,offset){return data[offset]|data[offset+1]<<8}
function hex(data){return[...data].map(byte=>byte.toString(16).padStart(2,"0")).join("")}
function hexBytes(value){const bytes=new Uint8Array(value.length/2);for(let i=0;i<bytes.length;i++)bytes[i]=parseInt(value.slice(i*2,i*2+2),16);return bytes}
function escapeHtml(value){return String(value).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;")}
function setResult(title,text,kind=""){el.title.textContent=title;el.text.textContent=text;el.result.className=`panel result ${kind}`;if(kind!=="ok")el.stats.hidden=true}
function notice(title,text,kind=""){el.notice.className=`notice ${kind}`;el.noticeTitle.textContent=title;el.noticeText.textContent=` ${text}`}
function log(message){const stamp=new Date().toLocaleTimeString();el.log.textContent=`${stamp} ${message}\n${el.log.textContent}`.slice(0,12000)}
function availableRepeaters(){const all=[...state.saved,...state.contacts.filter(contact=>contact.type===TYPE_REPEATER)];const query=state.search.toLowerCase();return[...new Map(all.map(item=>[item.key,item])).values()].filter(item=>!query||`${item.name} ${item.key} ${item.prefix}`.toLowerCase().includes(query))}
function updateUi(){const connected=state.connected;const hasRepeaters=availableRepeaters().length>0;el.connect.disabled=connected;el.disconnect.disabled=!connected;el.repeater.disabled=!hasRepeaters;el.password.disabled=!connected;el.syncTime.disabled=!connected;el.status.disabled=!connected||!hasRepeaters;el.save.disabled=!connected||!el.repeater.value;el.remove.disabled=!el.repeater.value;el.connection.textContent=connected?"Verbunden":"Nicht verbunden"}
function wait(codes,timeout=7000){return new Promise((resolve,reject)=>{const item={codes,resolve,reject};item.timer=setTimeout(()=>{state.waiters=state.waiters.filter(entry=>entry!==item);reject(new Error("Keine Antwort vom Companion."))},timeout);state.waiters.push(item)})}
function notify(event){const data=new Uint8Array(event.target.value.buffer,event.target.value.byteOffset,event.target.value.byteLength);log(`RX ${hex(data)}`);handleContactPacket(data);if(data[0]===RESP.CONTACTS_END)log("RX CONTACTS_END");const index=state.waiters.findIndex(item=>item.codes.includes(data[0])||data[0]===RESP.ERROR);if(index<0)return;const[item]=state.waiters.splice(index,1);clearTimeout(item.timer);if(data[0]===RESP.ERROR)item.reject(new Error(`Companion-Fehler ${data[1]??"?"}`));else item.resolve(data)}
async function send(data){if(!state.rx)throw new Error("Nicht verbunden.");log(`TX ${hex(data)}`);if(typeof state.rx.writeValueWithResponse==="function")await state.rx.writeValueWithResponse(data);else await state.rx.writeValue(data)}
async function syncTime(){try{el.syncTime.disabled=true;notice("Zeit-Sync ...","Setze die Gerätezeit auf die aktuelle Handy-/PC-Zeit.","warn");const response=wait([RESP.OK]);const data=new Uint8Array(5);data[0]=CMD.SET_DEVICE_TIME;const seconds=Math.floor(Date.now()/1000);data[1]=seconds&255;data[2]=seconds>>>8&255;data[3]=seconds>>>16&255;data[4]=seconds>>>24&255;await send(data);await response;notice("Zeit synchronisiert","Die Gerätezeit wurde erfolgreich gesetzt.","ok")}catch(error){notice("Zeit-Sync fehlgeschlagen",error.message,"error")}finally{el.syncTime.disabled=!state.connected}}
function readName(data){const zero=data.indexOf(0);return new TextDecoder().decode(zero<0?data:data.slice(0,zero)).trim()||"Unbenannter Repeater"}
function handleContactPacket(data){if(data[0]!==RESP.CONTACT||data.length<132)return;const key=hex(data.slice(1,33));const contact={key,prefix:key.slice(0,12),type:data[33],name:readName(data.slice(100,132))};state.contacts.push(contact)}
async function requestDeviceInfo(){log("Protokoll: DEVICE_QUERY");const response=wait([RESP.DEVICE_INFO]);await send(Uint8Array.of(CMD.DEVICE_QUERY,3));await response;log("Protokoll: DEVICE_INFO erhalten");const name=new TextEncoder().encode("MeshCore Repeater Status");const appStart=new Uint8Array(8+name.length);appStart[0]=CMD.APP_START;appStart[1]=1;appStart.set(name,8);const ready=wait([RESP.SELF_INFO]);await send(appStart);await ready;log("Protokoll: APP_START bestätigt")}
async function loadContacts(){state.contacts=[];notice("Synchronisiere ...","Lade Repeater-Kontakte vom Companion.","warn");log("Protokoll: GET_CONTACTS (Timeout 60 s)");const done=wait([RESP.CONTACTS_END],60000);await send(Uint8Array.of(CMD.GET_CONTACTS,0,0,0,0));await done;log(`Kontakt-Sync abgeschlossen: ${state.contacts.length} Frames`);persistSaved();renderRepeaters()}
async function openGatt(){for(let attempt=1;attempt<=4;attempt++){try{log(`GATT-Verbindung Versuch ${attempt}/4`);const server=state.device.gatt.connected?state.device.gatt:await state.device.gatt.connect();const service=await server.getPrimaryService(BLE_SERVICE);state.rx=await service.getCharacteristic(BLE_RX);state.tx=await service.getCharacteristic(BLE_TX);state.tx.addEventListener("characteristicvaluechanged",notify);await state.tx.startNotifications();await new Promise(resolve=>setTimeout(resolve,500));log("GATT und Notifications bereit");return}catch(error){log(`GATT-Fehler: ${error.message}`);if(attempt===4)throw error;await new Promise(resolve=>setTimeout(resolve,1000*attempt))}}}
async function connect(){try{if(!window.isSecureContext)throw new Error("Web Bluetooth benötigt localhost oder HTTPS.");state.intentionalDisconnect=false;setResult("Verbinde ...","Bluetooth-Gerät auswählen.","waiting");notice("Verbinde ...","Bluetooth-Gerät auswählen.","warn");log("Bluetooth-Geräteauswahl gestartet");state.device=await navigator.bluetooth.requestDevice({filters:[{services:[BLE_SERVICE]}],optionalServices:[BLE_SERVICE]});state.device.addEventListener("gattserverdisconnected",handleUnexpectedDisconnect);await openGatt();state.connected=true;updateUi();notice("Verbunden","Companion verbunden, synchronisiere Kontakte.","ok");await requestDeviceInfo();await loadContacts();setResult("Bereit",`${availableRepeaters().length} Repeater gespeichert/gefunden.`,"ok");notice("Bereit","Synchronisierung abgeschlossen.","ok")}catch(error){log(`Verbindungsablauf fehlgeschlagen: ${error.stack||error.message}`);disconnect();setResult("Verbindung fehlgeschlagen",error.message,"error");notice("Fehler",error.message,"error")}}
async function handleUnexpectedDisconnect(){if(state.intentionalDisconnect)return;log("GATT-Verbindung unerwartet getrennt");state.connected=false;state.rx=null;state.tx=null;updateUi();notice("Verbindung unterbrochen","Versuche, den Companion automatisch wieder zu verbinden ...","warn");for(let attempt=1;attempt<=3&&!state.intentionalDisconnect;attempt++){try{await openGatt();state.connected=true;updateUi();notice("Wieder verbunden","BLE-Verbindung steht wieder.","ok");await requestDeviceInfo();await loadContacts();return}catch(error){log(`Wiederverbindung ${attempt} fehlgeschlagen: ${error.message}`);if(attempt===3)notice("Verbindung verloren","Automatische Wiederverbindung fehlgeschlagen. Bitte erneut verbinden.","error");await new Promise(resolve=>setTimeout(resolve,1000*attempt))}}}
function renderRepeaters(){const query=state.search.toLowerCase();const matches=items=>items.filter(item=>!query||`${item.name} ${item.key} ${item.prefix}`.toLowerCase().includes(query));const saved=matches(state.saved);const savedKeys=new Set(state.saved.map(item=>item.key));const found=matches(state.contacts.filter(item=>item.type===TYPE_REPEATER&&!savedKeys.has(item.key)));const option=item=>`<option value="${item.key}">${escapeHtml(item.name)} (${item.prefix})</option>`;const groups=[];if(saved.length)groups.push(`<optgroup label="Gespeichert">${saved.map(option).join("")}</optgroup>`);if(found.length)groups.push(`<optgroup label="Neu gefunden">${found.map(option).join("")}</optgroup>`);el.repeater.innerHTML=groups.join("")||"<option>Keine passenden Repeater</option>";updateUi()}
function selectedRepeater(){return availableRepeaters().find(item=>item.key===el.repeater.value)}
function saveSelected(){const item=selectedRepeater();if(!item)return;if(!state.saved.some(saved=>saved.key===item.key)){state.saved.push(item);persistSaved()}renderRepeaters();setResult("Gespeichert",`${item.name} wurde lokal gespeichert.`,"ok")}
function removeSelected(){const key=el.repeater.value;state.saved=state.saved.filter(item=>item.key!==key);persistSaved();renderRepeaters();setResult("Entfernt","Der Repeater wurde aus der lokalen Liste entfernt.","ok")}
function exportRepeaters(){const payload={format:"meshcore-repeater-list",version:1,exported_at:new Date().toISOString(),repeaters:state.saved};const blob=new Blob([JSON.stringify(payload,null,2)],{type:"application/json"});const link=document.createElement("a");link.href=URL.createObjectURL(blob);link.download="meshcore-repeater-list.json";link.click();URL.revokeObjectURL(link.href)}
async function importRepeaters(event){const file=event.target.files?.[0];event.target.value="";if(!file)return;try{const payload=JSON.parse(await file.text());if(payload?.format!=="meshcore-repeater-list"||!Array.isArray(payload.repeaters))throw new Error("Unbekanntes Repeater-Listenformat.");const imported=payload.repeaters.filter(validRepeater);state.saved=[...new Map([...state.saved,...imported].map(item=>[item.key,item])).values()];persistSaved();renderRepeaters();setResult("Importiert",`${imported.length} Repeater übernommen.`,"ok")}catch(error){setResult("Import fehlgeschlagen",error.message,"error")}}
async function login(contact,password){notice("Authentifizierung ...","Admin-Zugang wird über das Mesh geprüft.","warn");const response=wait([RESP.LOGIN_SUCCESS,RESP.LOGIN_FAIL],12000);const pass=new TextEncoder().encode(password);const data=new Uint8Array(33+pass.length);data[0]=CMD.SEND_LOGIN;data.set(hexBytes(contact),1);data.set(pass,33);await send(data);const result=await response;if(result[0]===RESP.LOGIN_FAIL)throw new Error("Repeater hat das Passwort abgelehnt.")}
async function status(){const key=el.repeater.value;const contact=selectedRepeater();if(!key||!contact)return;try{el.status.disabled=true;setResult("Sende Statusabfrage ...","Der Companion sendet die Anfrage ins Mesh.","waiting");await login(key,el.password.value);const response=wait([RESP.STATUS],45000);await send(Uint8Array.of(CMD.SEND_STATUS_REQ,...hexBytes(key)));setResult("Warte auf Antwort ...","Der Repeater muss über das Mesh antworten.","waiting");notice("Warte auf Repeater ...","Bis zu 45 Sekunden für Hin- und Rückweg.","warn");renderStatus(await response,contact)}catch(error){setResult("Keine Antwort",error.message,"error");notice("Abfrage fehlgeschlagen",error.message,"error")}finally{el.status.disabled=!state.connected}}
function formatUptime(seconds){const days=Math.floor(seconds/86400),hours=Math.floor(seconds%86400/3600),minutes=Math.floor(seconds%3600/60);return`${days}d ${String(hours).padStart(2,"0")}:${String(minutes).padStart(2,"0")}`}
function renderStatus(data,contact){const stats=data.slice(8);const rows=[["Repeater",contact.name],["Batterie",`${u16(stats,0)} mV`],["TX-Warteschlange",u16(stats,2)],["Pakete empfangen",u32(stats,8)],["Pakete gesendet",u32(stats,12)],["Uptime",formatUptime(u32(stats,20))],["Flood gesendet",u32(stats,24)],["Flood empfangen",u32(stats,32)],["Letzter RSSI",`${s16(stats,6)} dBm`],["Letzter SNR",`${(s16(stats,42)/4).toFixed(2)} dB`]];el.stats.innerHTML=rows.map(([label,value])=>`<div><dt>${label}</dt><dd>${value}</dd></div>`).join("");el.stats.hidden=false;setResult("Antwort erhalten",`${contact.name} hat geantwortet.`,"ok")}
function disconnect(){state.intentionalDisconnect=true;state.connected=false;state.rx=null;state.tx=null;state.contacts=[];state.waiters.splice(0).forEach(item=>{clearTimeout(item.timer);item.reject(new Error("Verbindung getrennt."))});try{if(state.device?.gatt?.connected)state.device.gatt.disconnect()}catch{}updateUi();renderRepeaters();el.connection.textContent="Nicht verbunden";notice("Getrennt","Der Companion ist nicht verbunden.","")}
fetch("version.json").then(response=>response.json()).then(metadata=>{el.version.textContent=`v${metadata.version}`}).catch(()=>{});el.connect.addEventListener("click",connect);el.disconnect.addEventListener("click",disconnect);el.syncTime.addEventListener("click",syncTime);el.status.addEventListener("click",status);el.repeater.addEventListener("change",updateUi);el.repeaterSearch.addEventListener("input",event=>{state.search=event.target.value.trim();renderRepeaters()});el.save.addEventListener("click",saveSelected);el.remove.addEventListener("click",removeSelected);el.export.addEventListener("click",exportRepeaters);el.import.addEventListener("click",()=>el.importFile.click());el.importFile.addEventListener("change",importRepeaters);renderRepeaters();updateUi();notice("Bereit","Noch keine Verbindung aufgebaut.");if(!("bluetooth"in navigator)){el.support.textContent="Web Bluetooth ist in diesem Browser nicht verfügbar. Chrome oder Edge verwenden.";el.connect.disabled=true}
